#!/usr/bin/env bash
# Author: Charles Oblender https://github.com/oblende
currentVersion="1.0.3"
configuredClient=""

dvdburn() {
	counter=$4
	countlim=$5
	while [ "$counter" -eq $countlim ]
	do
		if [[ $(echo "$1" | grep "dev" | wc -l) -eq 0 ]]
		then
			echo "DVD or BluRay burning requires device from /dev."
			exitcode=1
			cleanup $exitcode
		fi
        	growisofs -Z "$1"=$2
        	counter=0
        	counter=$(ps -A | grep $3 | wc -l)
        	if [[ $counter -eq $countlim ]]
        	then
                	read -p "Insert next disc and press Enter:"
                	echo >&7
        	fi
	done
}

cdburn() {
	counter=$4
	countlim=$5
	while [ "$counter" -eq $countlim ]
	do
		if [[ $(uname | grep "FreeBSD" | wc -l) -gt 0 ]]
		then
			if [[ $(echo "$1" | grep "dev" | wc -l) -gt 0 ]]
			then
				echo "CD burning requires SCSI address in the form of b,t,l. Please use cdrecord -scanbus for a list of possible SCSI addresses."
				exitcode=1
				cleanup $exitcode
			fi
		elif [[ $(uname | grep "Linux" | wc -l) -gt 0 ]]
		then
			if [[ $(echo "$1" | grep "dev" | wc -l) -eq 0 ]]
			then
				# Chances are if it's Linux then wodim is being used and requires /dev/srX instead of SCSI address
				echo "CD burning in Linux requires device from /dev."
				exitcode=1
				cleanup $exitcode
			fi
		fi
		cdrecord dev=$1 driveropts=burnfree -tao -multi -eject -data $2 #Turned burnfree on just in case
		counter=0
		counter=$(ps -A | grep $3 | wc -l)
		if [[ $counter -eq $countlim ]]
		then
			read -p "Insert next disc and press Enter:"
			echo >&7
		fi
	done
}

cleanup() {
	kill $tarpid
	rm $pipename
	rm $fifoname

	exit $1
}


## This function determines which http get tool the system has installed and returns an error if there isnt one
getConfiguredClient()
{
  if  command -v curl &>/dev/null; then
    configuredClient="curl"
  elif command -v wget &>/dev/null; then
    configuredClient="wget"
  elif command -v http &>/dev/null; then
    configuredClient="httpie"
  elif command -v fetch &>/dev/null; then
    configuredClient="fetch"
  else
    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
    return 1
  fi
}

## Allows to call the users configured client without if statements everywhere
httpGet()
{
  case "$configuredClient" in
    curl)  curl -A curl -s "$@" ;;
    wget)  wget -qO- "$@" ;;
    httpie) http -b GET "$@" ;;
    fetch) fetch -q "$@" ;;
  esac
}

update()
{
  # Author: Alexander Epstein https://github.com/alexanderepstein
  # Update utility version 1.2.0
  # To test the tool enter in the defualt values that are in the examples for each variable
  repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
  githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
  nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
  latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option

  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
    echo "Error: update utility has not been configured correctly." >&2
    exit 1
  elif [[ $latestVersion == "" ]]; then
    echo "Error: no active internet connection" >&2
    exit 1
  else
    if [[ "$latestVersion" != "$currentVersion" ]]; then
      echo "Version $latestVersion available"
      echo -n "Do you wish to update $repositoryName [Y/n]: "
      read -r answer
      if [[ "$answer" == [Yy] ]]; then
        cd ~ || { echo 'Update Failed'; exit 1; }
        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
        git clone "https://github.com/$githubUserName/$repositoryName" || { echo "Couldn't download latest version"; exit 1; }
        cd $repositoryName || { echo 'Update Failed'; exit 1; }
        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
        chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
        ./$nameOfInstallFile "update" || exit 1
        cd ..
        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
      else
        exit 1
      fi
    else
      echo "$repositoryName is already the latest version"
    fi
  fi
}

checkInternet()
{
  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
}

usage()
{
  cat <<EOF
Bak2dvd
Description: A script to write tar archives to optical disc.
Usage: bak2dvd [flags] -t "[arguments]"
  -u  Update Bash-Snippet Tools
  -h  Show the help
  -v  Get the tool version
  -d  Sets the optical drive to use
  -t  Parameters to pass to tar

 Disc technology flags are:

  -cd       for cd-rom
  -dvd      for single layer DVD+R
  -dvd-dl   for dual layer DVD+R
  -dvd-r    for single layer DVD-R
  -bd       for single layer BluRay
  -bd-dl    for dual layer BluRay

 Preset tar parameters are -cvpML and -f

Example:
   bak2dvd -d /dev/sr0 -dvd -t "-C $HOME Documents"
   bak2dvd -d 1,0,0 -cd -t "-C $HOME Documents"
EOF
}


options=0

while test $# -gt 0; do
  case "$1" in
    \?) echo "Invalid option: -$1" >&2
        exit 1
        ;;
   -h|--help)  usage
        exit 0
        ;;
    -v)  echo "Version $currentVersion"
        exit 0
        ;;
    -u)  getConfiguredClient || exit 1
        checkInternet || exit 1
        update
        exit 0
        ;;
    -d)
	shift
	if test $# -gt 0; then
		device=$1
	else
		echo "No optical device specified" >&2
		exit 1
	fi
	shift
	options=1
	;;
     -dvd)
		tracklen="4580000" # DVD+R capacity - 10M
		shift
		options=1
		;;
     -dvd-dl)
		tracklen="8337408" # DVD+R DL capacity - 10M
		shift
		options=1
		;;
     -dvd-r)
		tracklen="4585536" #DVD-R single layer capacity -10M
		shift
		options=1
		;;
     -bd)
		tracklen="24428544" # This should be 10M less than total
		shift
		options=1
		;;
     -bd-dl)
		tracklen="48867328" #same as above but dual layer
		shift
		options=1
		;;
     -cd)
		tracklen="712702" #700M cd-rom capacity - 4k, 10M is not an insigficant amout at this storage capacity!
		shift
		options=1
		;;
     -t)
		shift
		if test $# -gt 0; then
			taropts=$1
		else
			echo "No options to tar specified." >&2
			exit 1
		fi
		shift
		options=1
		;;
    :)  echo "Option -$1 requires an argument." >&2
        exit 1
        ;;
  esac
done

# special set of first arguments that have a specific behavior across tools
if [[ $# == "0" && $options == "0" ]]; then
  usage ## if calling the tool with no flags and args chances are you want to return usage
  exit 0
elif [[ $# == "1" ]]; then
  if [[ $1 == "update" ]]; then
    getConfiguredClient || exit 1
    checkInternet || exit 1
    update || exit 1
    exit 0
  elif [[ $1 == "help" ]]; then
    usage
    exit 0
  fi
fi

## The rest of the conditions and code would go here
## Make sure to use checkInternet at least once before any time httpGet will be called.
## Make sure to call getConfiguredClient at least once before ever calling checkInternet.

pipename="/tmp/$RANDOM.pipe"
fifoname="/tmp/$RANDOM.fifo"
#changed from mknod to mkfifo to  make script more cross platform
mkfifo $pipename
mkfifo $fifoname
# Asign the fifo to a file descriptor. No need for ugly cat hack, and it actually works!
exec 7<>$fifoname
# FreeBSD needs to use gtar
case $(uname) in
	Linux)
		tar -cvpML $tracklen -f $pipename $taropts <&7 &
		tarpid=$!
		countlimit=1
		;;
	FreeBSD)
		gtar -cvpML $tracklen -f pipename $taropts <&7 &
		tarpid=$!
		countlimit=2
		;;
esac

count=$(ps -A | grep $tarpid | wc -l)
# Check that tar is alive and prompt for media
if [[ $count -eq $countlimit ]]
then
	read -p "Insert media and press Enter:"
	#call appropriate burning function here
	if [[ $tracklen -le 712702 ]]
	then
		cdburn $device $pipename $tarpid $count $countlimit
	else
		dvdburn $device $pipename $tarpid $count $countlimit
	fi

else
	# otherwise something has gone wrong and we need to stop
	echo
	echo "Tar has died unexpectedly." >&2
	# Call cleanup function here
	exitcode=1
	cleanup $exitcode
fi
exitcode=0
cleanup $exitcode

exit 0
