#!/bin/bash
# REQUIRED PACKAGES: curl

# USAGE: youtubeviewer [YouTube channel]

# EXAMPLE: youtubeviewer pewdiepie
rm -rf $HOME/.cache/ytview/


# Get the video titles
channelview() {
	read -p "Choose your video player: " player

	mkdir -p $HOME/.cache/ytview/channels/$channel
	curl -s https://www.youtube.com/user/$channel/videos | grep "Duration" | awk '{print $10 " " $11 " " $12 " " $13 " " $14 " " $15 " " $16 " " $17 " " $18 " " $19 " " $20 " " $21 " " $22 " " $23 " " $24 " " $25 " " $26 " " $27 " " $29}' | sed 's/aria-describedby="description-id.*//' | sed s/title=// | sed 's/"//' | sed 's/"//' | awk '{printf "%s.\t%s\n",NR,$0}' > $HOME/.cache/ytview/channels/$channel/titles.txt

	# Get the video urls
	curl -s https://www.youtube.com/user/$channel/Videos | grep "watch?v=" | awk '{print $6}' | sed s/spf-link//  | sed s/href=// | sed 's/"//' | sed 's/"//' | sed '/^\s*$/d' | sed 's/\//https:\/\/www.youtube.com\//' |  awk '{printf "%s.\t%s\n",NR,$0}' > $HOME/.cache/ytview/channels/$channel/urls.txt 


	# Print 20 first video titles for the user to choose from
	head $HOME/.cache/ytview/channels/$channel/titles.txt -n 20
	# Prompt the user for video number
	read -p "Choose a video: " titlenumber



	# Play the video with your player
	$player $(grep $titlenumber  $HOME/.cache/ytview/channels/$channel/urls.txt | awk '{print $2}') # grep is not needed here but I'm lazy
}

searchview() {
	read -p "Choose your video player: " player
	
	search=$(echo $search |sed -e "s/ /+/")
	mkdir -p $HOME/.cache/ytview/searches/$search
	
	#Get video titles
	curl -s https://www.youtube.com/results\?search_query\=$search | grep "Duration" | awk '{print $13 " " $14 " " $15 " " $16 " " $17 " " $18 " " $19 " " $20 " " $21 " " $22 " " $23 " " $24 " " $25 " " $26 " " $27 " " $29}' | sed 's/aria-describedby="description-id.*//' | sed s/title=// | sed 's/"//' | sed 's/"//' | sed s/spf-link// | sed 's/data-sessionlink=itct*.//' |  sed s/spf-prefetch// | tail -n 17 | sed 's/rel="//' | sed 's/"//' | awk '{printf "%s.\t%s\n",NR,$0}' > $HOME/.cache/ytview/searches/$search/titles.txt
	
	#Get video urls
	curl -s https://www.youtube.com/results\?search_query\=$search | grep "watch?v=" | awk '{print $5}' | sed s/vve-check// | sed 's/href="/https:\/\/www.youtube.com/' | sed 's/"//' | sed s/class="yt-uix-tile-link"// |sed '/^\s*$/d' | awk '{printf "%s.\t%s\n",NR,$0}' > $HOME/.cache/ytview/searches/$search/urls.txt
	#Print 20 first video titles for the user to choose from
	head $HOME/.cache/ytview/searches/$search/titles.txt -n 18
	
	#Let the user choose the video number
	read -p "Choose a video: " titlenumber
	
	#Play the video with your favorite player
	$player $(grep $titlenumber  $HOME/.cache/ytview/searches/$search/urls.txt | awk '{print $2}')
	


}

usage() {
	echo "Usage: ytview [flag] [string]"
	echo "     -s Searches youtube"
	echo "     -c Shows the latest videos of a channel;"
}



while getopts c:s:h*: option
do
	case "${option}" in
		s) search=${OPTARG} && searchview ;;
		c) channel=${OPTARG} && channelview ;;
		h) usage ;;
		*) usage ;;
	esac
done

