#!/bin/bash
# REQUIRED PACKAGES: curl mpv

# USAGE: ytchannel [YouTube channel]

# EXAMPLE: ytchannel pewdiepie
rm -rf /home/$USER/.cache/ytchannel/
mkdir -p /home/$USER/.cache/ytchannel/channels/$1

# Get the video titles
lynx --dump "https://youtube.com/user/$1/Videos" | grep "Duration" > /home/$USER/.cache/ytchannel/channels/$1/titles.txt

# Get the video urls
lynx --dump "https://youtube.com/user/$1/Videos" | grep "https://www.youtube.com/watch?v=" > /home/$USER/.cache/ytchannel/channels/$1/urls.txt

# Print 20 first video titles for the user to choose from
head /home/$USER/.cache/ytchannel/channels/$1/titles.txt -n 20 --quiet
# Prompt the user for video number
read -p "Choose a video: " titlenumber

# Play the video with mpv
mpv $(grep $titlenumber  /home/$USER/.cache/ytchannel/channels/$1/urls.txt | awk '{print $2}') # grep is not needed here but I'm lazy


